[package]
name = "hyperion"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.48"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }
